#!/usr/bin/env python3
"""Generate every skill target and every skill pointer from the sources in `.skills/`.

WHY THIS EXISTS
---------------
A skill is shown to a tool as one line - its `description` - and read by a human as its body, and the
same text has to appear in four places: `.agents/skills/<name>/SKILL.md` (the single real target),
`.agents/skills/<name>/_meta.json`, the `@`-import list in `GEMINI.md` for a tool that cannot read
that directory, and a pointer rule in `.windsurf/rules/` for the same reason. Four copies of one
paragraph are four places for it to drift, so none of them is written by hand: the source is
`.skills/<name>/` and this program is what turns it into all four.

WHAT IT DOES NOT DO
-------------------
It does not rewrite a skill it did not author. `skill-creator`-style skills that live only in
`.agents/skills/` are discovered and given the same pointer and the same import line, and nothing
else about them is touched. And it does not delete anything unless asked: `--prune` is the only way
a generated pointer goes away, because a pointer left behind is visible and a skill deleted by a
generator is not.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
import zlib
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / ".skills"
TARGET = ROOT / ".agents" / "skills"
GEMINI = ROOT / "GEMINI.md"
WINDSURF = ROOT / ".windsurf" / "rules"
ORGANIZATION = "UAK35"
PLATFORM = "codebuff"

GEMINI_BEGIN = "<!-- SKILLS-IMPORT:BEGIN -->"
GEMINI_END = "<!-- SKILLS-IMPORT:END -->"
WINDSURF_MARK = "generated by python .skills/_sync.py"

REQUIRED = ("name", "version", "description", "instructions")


# ---------------------------------------------------------------------------
# the source
# ---------------------------------------------------------------------------


class SourceError(Exception):
    """A skill.yaml this program will not guess at."""


def parse_yaml(text: str) -> dict:
    """The subset of YAML these files use: `key: value`, and sections by indentation.

    A full YAML reader would be a dependency for a handful of keys of structure, and a silent
    misread is worse than a refusal - so a line this does not understand is an error rather than a
    guess. There are no lists and no inline maps; a value is a scalar or a section.
    """
    data: dict = {}
    stack: list[tuple[int, dict]] = [(-1, data)]

    for number, raw in enumerate(text.splitlines(), start=1):
        line = raw.split(" #")[0].rstrip()
        if not line.strip() or line.lstrip().startswith("#"):
            continue

        indent = len(line) - len(line.lstrip())

        if ":" not in line:
            raise SourceError(f"line {number}: not a `key: value` line: {line!r}")

        key, _, value = line.partition(":")
        key = key.strip()
        value = value.strip().strip('"')

        while len(stack) > 1 and indent <= stack[-1][0]:
            stack.pop()

        if indent <= stack[-1][0]:
            raise SourceError(f"line {number}: indented under nothing: {line!r}")

        section = stack[-1][1]

        if value:
            section[key] = value
            continue

        child: dict = {}
        section[key] = child
        stack.append((indent, child))

    return data


def load(name: str) -> dict:
    directory = SOURCE / name
    manifest = directory / "skill.yaml"

    if not manifest.is_file():
        raise SourceError(f"{manifest.relative_to(ROOT).as_posix()} is missing")

    data = parse_yaml(manifest.read_text(encoding="utf-8"))
    missing = [key for key in REQUIRED if not data.get(key)]

    if missing:
        raise SourceError(f"{name}: {manifest.name} has no {', '.join(missing)}")

    if "files" in data:
        raise SourceError(
            f"{name}: `files:` is declared and this program does not copy files - add that support "
            "rather than leaving the entries out silently"
        )

    instructions = directory / str(data["instructions"])
    if not instructions.is_file():
        raise SourceError(f"{name}: {data['instructions']} is missing")

    body = instructions.read_text(encoding="utf-8")
    sync = data.get("sync") if isinstance(data.get("sync"), dict) else {}
    freebuff = sync.get("freebuff") if isinstance(sync.get("freebuff"), dict) else {}

    return {
        "source": name,
        "target": str(freebuff.get("name_override") or name),
        "data": data,
        "body": body,
        "hash": hashlib.sha256(body.encode("utf-8")).hexdigest()[:16],
        "modified": max(manifest.stat().st_mtime, instructions.stat().st_mtime),
        "gemini": str(sync.get("gemini", {}).get("enabled", "true")).lower() != "false"
        if isinstance(sync.get("gemini"), dict)
        else True,
        "windsurf": str(sync.get("windsurf", {}).get("enabled", "true")).lower() != "false"
        if isinstance(sync.get("windsurf"), dict)
        else True,
    }


def sources() -> list[dict]:
    if not SOURCE.is_dir():
        return []
    return [load(path.name) for path in sorted(SOURCE.iterdir()) if path.is_dir() and not path.name.startswith("_")]


# ---------------------------------------------------------------------------
# the targets
# ---------------------------------------------------------------------------


def frontmatter(skill: dict) -> str:
    data = skill["data"]
    lines = [
        "---",
        f"name: {skill['target']}",
        f'description: "{str(data["description"]).replace(chr(34), chr(39))}"',
    ]
    if data.get("license"):
        lines.append(f'license: "{data["license"]}"')
    lines.append("---")
    return "\n".join(lines)


def target_text(skill: dict) -> str:
    body = skill["body"].lstrip("\n")
    if body.startswith("---"):
        return body
    return frontmatter(skill) + "\n\n" + body


def meta_text(skill: dict) -> str:
    data = skill["data"]
    stamp = datetime.fromtimestamp(skill["modified"], tz=timezone.utc)
    meta = {
        "name": skill["target"],
        "version": str(data.get("version", "")),
        "description": str(data.get("description", "")),
        "author": str(data.get("author", ORGANIZATION)),
        "license": str(data.get("license", "MIT")),
        "date": stamp.strftime("%Y-%m-%d"),
        "updated_at": int(stamp.timestamp() * 1000),
        "tags": [tag.strip() for tag in str(data.get("tags", "")).split(",") if tag.strip()],
        "categories": [tag.strip() for tag in str(data.get("categories", "")).split(",") if tag.strip()],
        "organization": ORGANIZATION,
        "platform": PLATFORM,
        "id": zlib.crc32(skill["target"].encode("utf-8")),
        "source_hash": skill["hash"],
    }
    return json.dumps(meta, indent=2, ensure_ascii=False) + "\n"


def gemini_block(names: list[str]) -> str:
    lines = [GEMINI_BEGIN, "<!-- generated by python .skills/_sync.py — do not edit by hand -->"]
    lines += [f"@.agents/skills/{name}/SKILL.md" for name in names]
    lines.append(GEMINI_END)
    return "\n".join(lines)


def windsurf_text(skill: dict) -> str:
    return "\n".join(
        [
            "---",
            "trigger: model_decision",
            f'description: "{str(skill["data"]["description"]).replace(chr(34), chr(39))[:200]}"',
            "---",
            "",
            f"# {skill['target']}",
            "",
            f"Read the skill at `.agents/skills/{skill['target']}/SKILL.md` before acting on "
            f"{skill['data'].get('categories', 'this repository')} work.",
            "",
            f"<!-- {WINDSURF_MARK} -->",
            "",
        ]
    )


# ---------------------------------------------------------------------------
# writing
# ---------------------------------------------------------------------------


def present_targets() -> list[str]:
    if not TARGET.is_dir():
        return []
    return sorted(path.name for path in TARGET.iterdir() if (path / "SKILL.md").is_file())


def write(path: Path, text: str, dry_run: bool) -> bool:
    current = path.read_text(encoding="utf-8") if path.is_file() else None
    if current == text:
        return False
    print(f"{'would write' if dry_run else 'wrote'} {path.relative_to(ROOT).as_posix()}")
    if not dry_run:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8", newline="\n")
    return True


def block(text: str, begin: str, end: str, replacement: str) -> str:
    pattern = re.compile(re.escape(begin) + r".*?" + re.escape(end), re.DOTALL)
    if pattern.search(text) is None:
        return text.rstrip("\n") + "\n\n" + replacement + "\n"
    return pattern.sub(lambda _match: replacement, text)


def sync(dry_run: bool, prune: bool) -> int:
    found = sources()

    for skill in found:
        write(TARGET / skill["target"] / "SKILL.md", target_text(skill), dry_run)
        write(TARGET / skill["target"] / "_meta.json", meta_text(skill), dry_run)

    # After the writes, so a skill authored in place is discovered too. In a dry run this is the
    # listing as it stands, which is what the pointers that follow would be built from.
    names = present_targets()

    wanted = {f"{name}.windsurf.md" for name in names}
    if WINDSURF.is_dir():
        for rule in sorted(WINDSURF.glob("*.windsurf.md")):
            if rule.name in wanted or WINDSURF_MARK not in rule.read_text(encoding="utf-8"):
                continue
            if not prune:
                print(f"stale pointer: {rule.relative_to(ROOT).as_posix()} (pass --prune to remove it)")
                continue
            print(f"removing {rule.relative_to(ROOT).as_posix()}")
            if not dry_run:
                rule.unlink()

    by_name = {skill["target"]: skill for skill in found}
    for name in names:
        if name in by_name and by_name[name]["windsurf"]:
            write(WINDSURF / f"{name}.windsurf.md", windsurf_text(by_name[name]), dry_run)

    imported = [name for name in names if name not in by_name or by_name[name]["gemini"]]
    if GEMINI.is_file():
        text = GEMINI.read_text(encoding="utf-8")
        write(GEMINI, block(text, GEMINI_BEGIN, GEMINI_END, gemini_block(imported)), dry_run)

    print(f"{len(found)} skill(s) authored in .skills/, {len(names)} target(s) in .agents/skills/")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="_sync.py", description="Generate skill targets and pointers.")
    parser.add_argument("--dry-run", action="store_true", help="show what would change, write nothing")
    parser.add_argument("--prune", action="store_true", help="also remove a generated pointer whose skill is gone")
    args = parser.parse_args(argv)

    if sys.version_info < (3, 9):
        print("this program needs Python 3.9 or newer")
        return 1

    try:
        return sync(args.dry_run, args.prune)
    except SourceError as error:
        print(f"[FAIL] {error}")
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
